### ISSUE TITLE
Vagrant setup is unsuccessful

### ISSUE THREAD

**Issue by StephenKappel** [prakhar1989/csds-material#12]
I'm running vagrant 1.8.1 on OS X El Capitan. Following the steps provided in SETUP.md do not work. 

The `vagrant` directory in the vm is not linked to the directory of the host where `Vagrantfile` resides, and the `postinstall.sh` is left in the `vagrant` directory. In the `vagrant up` output, there are several errors. I'm not sure which ones are the critical ones, so I'm including several of them below:

`GuestAdditions versions on your host (5.0.14) and guest (4.2.0) do not match.`

`An error occurred during installation of VirtualBox Guest Additions 5.0.14. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.`

`==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory`

```
==> default: Downloading/unpacking protobuf
==> default:   Running setup.py egg_info for package protobuf
==> default:     
==> default:     no previously-included directories found matching 'google/protobuf/internal/import_test_package'
==> default:     warning: no previously-included files found matching 'google/protobuf/internal/*_pb2.py'
==> default:     warning: no previously-included files found matching 'google/protobuf/internal/*_test.py'
==> default:     warning: no previously-included files found matching 'google/protobuf/internal/*.proto'
==> default:     warning: no previously-included files found matching 'google/protobuf/internal/test_util.py'
==> default:     warning: no previously-included files matching '*_test.py' found under directory 'google'
==> default:     warning: no previously-included files matching '*_test.proto' found under directory 'google'
==> default:     warning: no previously-included files matching 'unittest*_pb2.py' found under directory 'google'
==> default:     warning: no previously-included files matching '*.dll' found anywhere in distribution
==> default:     warning: no previously-included files matching '*.pyc' found anywhere in distribution
==> default:     warning: no previously-included files matching '*.pyo' found anywhere in distribution
==> default:     warning: no previously-included files matching '*.so' found anywhere in distribution
```

**Comment by prakhar1989** [comment]
Can you clarify more on what part is unsuccessful? Does the VM not start or are you unable to SSH into it? I'm on El Capitan (virtualbox 5.0.12) and I can't reproduce your error. Also, what directory is `/vagrant` linked to?

**Comment by StephenKappel** [comment]
`vagrant up` completes (but with the above mentioned warnings), and I can ssh into the machine. But, once I'm in the machine, I don't see any of the files from the host machine's `csds-material` directory (where the Vagrantfile lives) in the `vagrant` folder on the VM.

**Comment by prakhar1989** [comment]
That's surprising. One easy way out probably is that you `git clone` the repo in your VM and then start working on it?

**Comment by StephenKappel** [comment]
I'll try that, but I'm worried that other things might be broken in the VM in addition to link to the host directory.

I tried setting up the VM on my Windows machine with clean installs of VirtualBox and Vagrant. I hit exactly the same problem as I did on my Mac. I even tried downgrading to Vagrant 1.7.4, but not luck. The vagrant vagrant-vbguest plugin didn't help either.

**Comment by StephenKappel** [comment]
I ended up just launching a t2.micro instance in EC2, running the Vagrantfile commands there (with `precise` changed to `trusty`), installing git, and cloning the csds-material repo there. This seems to be much less painful so far. I've got my fingers crossed that everything else goes smoothly!

**Comment by prakhar1989** [comment]
That's great! Let us know if you face more issues.

**Comment by StephenKappel** [comment]
Work around now documented in https://github.com/prakhar1989/csds-material/blob/ewu-csds/SETUP.md.
